services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.flask
    container_name: blender_api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 3
              capabilities: ["gpu"]
    privileged: true
    volumes:
      - workspace_data:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
      - TZ=${TZ}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_SERVICE_ACCOUNT_B64=${GOOGLE_SERVICE_ACCOUNT_B64}      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blender-api.rule=Host(`blender.plog.net`)"
      - "traefik.http.routers.blender-api.entrypoints=websecure"
      - "traefik.http.routers.blender-api.tls=true"
      - "traefik.http.routers.blender-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.blender-api.loadbalancer.server.port=80"

volumes:
  workspace_data:
    driver: local
